version: "2"
services:
  web:
    command: yarn start
    restart: always
    ports:
      - 8080:8080
    environment:
      PRODUCTION: 'true'

  backend:
    command: yarn start
    restart: always
    ports:
      - '3000:3000'
    environment:
      PRODUCTION: 'true'
