version: 2

defaults: &defaults
  working_directory: ~/project/doggies
  docker:
    - image: docker:17.05.0-ce-git

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run: docker version
      - run: docker-compose version

      - persist_to_workspace:
          root: ~/project
          paths:
            - doggies

  build-backend:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/backend.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/backend.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=backend -t backend backend
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/backend.tar backend
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/backend.tar

      - persist_to_workspace:
          root: ~/project
          paths:
            - doggies

  build-frontend:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/frontend.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/frontend.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=frontend -t frontend frontend
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/frontend.tar frontend
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/frontend.tar

      - persist_to_workspace:
          root: ~/project
          paths:
            - doggies

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Start container and verify it's working
          command:
            docker-compose up -d --build
            docker run --network container:backend \
              appropriate/curl --retry 10 --retry-delay 1 --retry-connrefused http://localhost:3000/
            docker run --network container:frontend \
              appropriate/curl --retry 10 --retry-delay 1 --retry-connrefused http://localhost:8080/

      - persist_to_workspace:
          root: ~/project
          paths:
            - doggies

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run: scp -r -o StrictHostKeyChecking=no dist/* $droplet:~/doggies
      - run: ssh $droplet '
            cd ~/doggies
            docker-compose build
            docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d'

workflows:
  version: 2
  install-and-parallel-build-test:
    jobs:
      - install
      - build-backend:
          requires:
            - install
      - build-frontend:
          requires:
            - install
      - test:
          requires:
            - build-backend
            - build-frontend
      - deploy:
          requires:
            - test
