version: 2

defaults: &defaults
  working_directory: ~/project/doggies
  docker:
    - image: docker:17.05.0-ce-git

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip=9.0.0-r1
            pip install \
              docker-compose==1.12.0 \
              awscli==1.11.76
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/app.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=app -t app .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/app.tar app
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/app.tar

      - persist_to_workspace:
          root: ~/project
          paths:
            - doggies

  build:
    <<: *defaults
    steps:
      - run:
          name: Start container and verify it's working
          command:
            docker-compose up -d --build
            docker run --network container:backend \
              appropriate/curl --retry 10 --retry-delay 1 --retry-connrefused http://localhost:3000/
            docker run --network container:frontend \
              appropriate/curl --retry 10 --retry-delay 1 --retry-connrefused http://localhost:8080/

      - persist_to_workspace:
          root: ~/project
          paths:
            - doggies

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project/
      - run: scp -r -o StrictHostKeyChecking=no dist/* $droplet:~/doggies

workflows:
  version: 2
  install-and-parallel-build-test:
    jobs:
      - install
      - build:
          requires:
            - install
      - deploy:
          requires:
            - install
            - build
