version: 2

defaults: &defaults
  working_directory: ~/project/doggies
  docker:
    - image: docker:17.05.0-ce-git

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip=9.0.0-r1
            pip install \
              docker-compose==1.12.0 \
              awscli==1.11.76
      - run: docker version
      - run: docker-compose version

      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/backend.tar
            - /caches/frontend.tar

      - run:
          name: Backend - Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/backend.tar | true
      - run:
          name: Backend - Build application Docker image
          command: |
            docker build --cache-from=backend -t backend backend
      - run:
          name: Backend - Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/backend.tar backend

      - run:
          name: Frontend - Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/frontend.tar | true
      - run:
          name: Frontend - Build application Docker image
          command: |
            docker build --cache-from=frontend -t frontend frontend
      - run:
          name: Frontend - Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/frontend.tar frontend
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/backend.tar
            - /caches/frontend.tar

      - run:
          name: Test - Start container and verify it's working
          command: |
            docker-compose up -d --build
            docker run --network container:backend \
              appropriate/curl --retry 10 --retry-delay 5 --retry-connrefused http://127.0.0.1:3000/
            docker run --network container:frontend \
              appropriate/curl --retry 10 --retry-delay 5 --retry-connrefused http://127.0.0.1:8080/

      - persist_to_workspace:
          root: ~/project
          paths:
            - doggies

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - deploy: scp -r -o StrictHostKeyChecking=no dist/* $droplet:~/doggies
      - run: ssh $droplet '
            cd ~/doggies
            docker-compose build
            docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d'

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
