version: 2

defaults: &defaults
  working_directory: ~/project/doggies
  docker:
    - image: circleci/node:latest

jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      - run:
          name: Start container and verify it's working
          command:
            docker-compose up -d --build
            docker run --network container:backend \
              appropriate/curl --retry 10 --retry-delay 1 --retry-connrefused http://localhost:3000/
            docker run --network container:frontend \
              appropriate/curl --retry 10 --retry-delay 1 --retry-connrefused http://localhost:8080/

      - persist_to_workspace:
          root: ~/project
          paths:
            - doggies

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project/
      - run: scp -r -o StrictHostKeyChecking=no dist/* $droplet:~/doggies

workflows:
  version: 2
  install-and-parallel-build-test:
    jobs:
      - build
      - deploy:
          requires:
            - build
