version: 2

defaults: &defaults
  working_directory: ~/project/doggies
  docker:
    - image: circleci/node:latest

# # This should go into custom primary image, here's only for the sake of explanation
# - run:
#     name: Install Docker client
#     command: |
#       set -x
#       VER="17.03.0-ce"
#       curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
#       tar -xz -C /tmp -f /tmp/docker-$VER.tgz
#       mv /tmp/docker/* /usr/bin
# # This should go into custom primary image, here's only for the sake of explanation
# - run:
#     name: Install Docker Compose
#     command: |
#       set -x
#       curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
#       chmod +x /usr/local/bin/docker-compose

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Install Docker Compose
          command: |
            set -x
            curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose

      - persist_to_workspace:
          root: ~/project
          paths:
            - doggies

  build:
    <<: *defaults
    steps:
      - run:
          name: Start container and verify it's working
          command:
            docker-compose up -d --build
            docker run --network container:backend \
              appropriate/curl --retry 10 --retry-delay 1 --retry-connrefused http://localhost:3000/
            docker run --network container:frontend \
              appropriate/curl --retry 10 --retry-delay 1 --retry-connrefused http://localhost:8080/

      - persist_to_workspace:
          root: ~/project
          paths:
            - doggies

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project/
      - run: scp -r -o StrictHostKeyChecking=no dist/* $droplet:~/doggies

workflows:
  version: 2
  install-and-parallel-build-test:
    jobs:
      - install
      - build:
          requires:
            - install
      - deploy:
          requires:
            - install
            - build
